#!/usr/bin/env bash
# Script to practice your debugg skills
sudo service nginx stop
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
