#!/usr/bin/env bash
#Nginx is running as the nginx user.

pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
