#!/usr/bin/env bash
# Nginx must be running as nginx
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/sites-available/default
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
